---
- name: Install common packages
  hosts: all
  become: true
  remote_user: ubuntu
  tags: common
  roles:
    - role: common

- name: Configure consul
  hosts: consul
  become: true
  remote_user: ubuntu
  tags: consuls
  roles:
    - role: consul

- name: Configure servers
  hosts: servers
  become: true
  remote_user: ubuntu
  tags: servers
  roles:
    - role: nomad

- name: Configure clients
  hosts: clients
  become: true
  remote_user: ubuntu
  tags: clients
  roles:
    - role: nomad

- name: Apply jobs
  hosts: servers[0]
  become: true
  remote_user: ubuntu
  tags: jobs
  roles:
    - role: jobs
