- name: install | docker packages
  block:
    - name: install | Install docker dependency packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release

    - name: configure | Add docker apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: configure | Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable

    - name: install | Install docker packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - docker-ce
        - docker-ce-cli
        - containerd.io

- name: install | kubernetes packages
  block:
    - name: install | Install dependency packages
      package:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - curl
        - apt-transport-https
        - gnupg2
        - ufw
        - ca-certificates
        - gnupg-agent
        - software-properties-common
        - nfs-common

    - name: Add kubernetes gpg apt key
      apt_key:
        url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
        state: present

    - name: Add kubernetes apt repo
      apt_repository:
        repo: "deb http://apt.kubernetes.io/ kubernetes-xenial main"
        state: present

    - name: install | Install kubernetes packages
      package:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - "kubeadm={{ kube_version }}"
        - "kubelet={{ kube_version }}"
        - "kubectl={{ kube_version }}"

- name: Remove swap files from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap
  command: swapoff -a
  changed_when: false # To-Do: Como saber se mudou algo?
  tags:
    - swap

- name: Restart docker
  service:
    name: docker
    state: restarted
    enabled: yes

