---
  - name: Restart docker
    service:
      name: docker
      state: restarted
      enabled: yes
  
  - name: Restart kubelet
    service:
      name: kubelet
      state: restarted
      enabled: yes
  
  - name: Restart ufw
    service:
      name: ufw
      state: restarted
      enabled: yes