---
- name: Register wg public key to variable
  command: cat /etc/wireguard/publickey
  register: wg_pub_key

- name: Create clients directory
  file:
    state: directory
    path: /etc/wireguard/clients
    recurse: true

- name: add clients
  include_tasks: add_client.yml
  loop: "{{ clients }}"
  loop_control:
    loop_var: client

- name: Restart wireguard service
  service:
    name: wg-quick@wg0
    state: restarted
