---
- name: install | Install required packages
  package:
    name: haproxy
    state: present

- name: configure | Move template of haproxy conf file
  template:
    src: templates/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg

- name: Start haproxy service
  service:
    name: haproxy
    state: restarted
    enabled: true

- name: check | Check if stats port number is accessible from the current host
  wait_for:
    host: localhost
    port: "{{ stats.port }}"
    state: started
    delay: 0
    timeout: 3
  ignore_errors: no
