---
- name: check | Check if cluster is initialized
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubernetes_init_stat
  changed_when: false

- name: configure | Execute join command on workers
  when: not kubernetes_init_stat.stat.exists
  command: "{{ kubectl_worker_join_command.stdout }}"

