---
- name: Pihole
  block:
    - name: Copy pihole job definition
      template:
        src: pihole.nomad
        dest: /etc/nomad/jobs/pihole.nomad
        owner: nomad
        group: nomad
        mode: 0755
    - name: Run job
      command: nomad job run -detach -address=http://192.168.0.30:4646 /etc/nomad/jobs/pihole.nomad

- name: Fabio
  block:
    - name: Copy fabio job definition
      template:
        src: fabio.nomad
        dest: /etc/nomad/jobs/fabio.nomad
        owner: nomad
        group: nomad
        mode: 0755
    - name: Run job
      command: nomad job run -detach -address=http://192.168.0.30:4646 /etc/nomad/jobs/fabio.nomad
