---
all:
  hosts:
    cp_lb_01:
      ansible_host:
    master_01:
      ansible_host: 34.239.106.22
    worker_01:
      ansible_host: 52.90.189.171

  children:
    cp_lbs:
      hosts:
        cp_lb_01:

    masters:
      hosts:
        master_01:

    workers:
      hosts:
        worker_01:

