---
all:
  vars:
    cluster_topology: "stacked_etcd"
  hosts:
    cp_lb_01:
      ansible_host: 54.161.87.198

    master_01:
      ansible_host: 54.174.191.39
    master_02:
      ansible_host: 34.227.142.77

    worker_01:
      ansible_host: 54.91.114.145
    worker_02:
      ansible_host: 54.174.114.250


  children:
    cp_lbs:
      hosts:
        cp_lb_01:

    masters:
      hosts:
        master_01:
        master_02:

    workers:
      hosts:
        worker_01:
        worker_02:
