---
- name: Configure control plane loadbalancers
  hosts: cp_lbs
  tags: loadbalancer
  remote_user: ubuntu
  become: true
  pre_tasks:
    - name: Gather facts on masters
      setup:
      delegate_to: "{{ item }}"
      delegate_facts: true
      loop: "{{ groups.masters }}"
  roles:
    - role: control-plane-lb

- name: Configure master nodes
  hosts: masters
  tags: master
  remote_user: ubuntu
  become: true
  pre_tasks:
    - name: Gather facts on loadbalancers
      setup:
      delegate_to: "{{ item }}"
      delegate_facts: true
      loop: "{{ groups.cp_lbs }}"
  roles:
    - role: common
    - role: master

- name: Configure worker nodes
  hosts: workers
  tags: worker
  remote_user: ubuntu
  become: true
  pre_tasks:
    - name: Get join command from masters
      command: kubeadm token create --print-join-command
      register: kubectl_worker_join_command
      changed_when: false
      delegate_to: "{{ groups.masters[0] }}"
  roles:
    - role: common
    - role: worker

- name: Apply common manifestos
  hosts: masters[0]
  tags: manifestos
  remote_user: ubuntu
  become: true
  roles:
    - role: manifestos

- name: Reset cluster
  hosts: masters,workers
  tags: reset
  remote_user: ubuntu
  become: true
  tasks:
    - name: kubeadm reset
      command: kubeadm reset -f
    - name: Clean etcd dir
      command: rm -rf /var/lib/etcd
    - name: Clean cni
      command: rm -rf /etc/cni

