---
cluster_topology: "single_master"
selected_network: "weave"
ignore_preflight_errors: "all"
taint_masters: false
nginx_ingress_controller: true

ports:
  - "22"
  - "80"
  - "443"
  - "2376"
  - "2379"
  - "2380"
  - "6783"
  - "6443"
  - "9099"
  - "10250"
  - "10255"
  - "8443"

